import os
import colorsys
from pathlib import Path
from loguru import logger

from config.config import config, _ConfigNode
from config.info import ROOT_DIR, SHELL_NAME, IS_WAYLAND
from config.bindings import (
    KeyBinding,
    apply_keybinding_overrides,
    I3_KEYBINDINGS,
)
from utils.colors import get_css_variable, hex_to_rgb01

from fabric.i3.widgets import get_i3_connection
from fabric.utils import exec_shell_command_async
# from fabric.i3.service import I3MessageType, I3Error

WM = "sway" if IS_WAYLAND else "i3"
CONFIG_DIR = Path.home() / f".config/{WM}"
CONFIG_PATH = CONFIG_DIR / "config"
CONFIG_GLOB_PATH = CONFIG_DIR / "conf.d"
BORDERS_CONF_PATH = CONFIG_GLOB_PATH / "borders.conf"
KEYBINDS_CONF_PATH = CONFIG_GLOB_PATH / "keybinds.conf"
GENERAL_CONF_PATH = CONFIG_GLOB_PATH / "general.conf"


def _reload_i3():
    try:
        i3_resp = get_i3_connection().send_command("reload")
        success = all(
            r.get("success", False) for r in i3_resp.reply if isinstance(r, dict)
        )
        if not success:
            logger.error("{} config failed to reload: {}", WM, i3_resp.reply)
    except Exception as e:
        logger.error("Error reloading {} config: {}", WM, e)


# Temporary workaround until my rounded-corners i3 patch is ready and picom shadows work as expected.
def ensure_vibrancy(hex_color: str, min_brightness=0.8, min_saturation=0.5) -> str:
    """Boosts brightness and saturation to ensure it stands out against backgrounds."""
    hex_color = hex_color.lstrip("#")

    # Hex -> RGB -> HSV
    r, g, b = hex_to_rgb01(hex_color=hex_color)
    h, s, v = colorsys.rgb_to_hsv(r, g, b)

    # Boost brightness and saturation if they are below threshold
    new_v = max(v, min_brightness)
    new_s = max(s, min_saturation)

    # HSV -> RGB -> Hex
    r, g, b = colorsys.hsv_to_rgb(h, new_s, new_v)
    return f"#{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}"


def generate_i3_border_theme_config(hex_color: str | None = None, reload: bool = False):
    ensure_i3_paths()
    STYLES_DIR = ROOT_DIR / "styles"
    COLORS_CSS_PATH = STYLES_DIR / "colors.css"

    theme_available = True

    if hex_color is None:
        if COLORS_CSS_PATH.exists():
            raw_color = get_css_variable(str(COLORS_CSS_PATH), "--primary")
            # raw_color = ensure_vibrancy(raw_color)
            hex_color = raw_color
        else:
            hex_color = "#5e81ac"
            theme_available = False

    logger.debug("Setting {} focused border color to {}", WM, hex_color)

    border_conf = [
        "# CAUTION: This file has been auto-generated by Zenith Shell.",
        "# Any manual changes WILL BE OVERWRITTEN on the next startup.",
        "# To change these bindings, use Settings or edit:",
        f"#   {ROOT_DIR}/config/config.json  OR",
        f"#   {ROOT_DIR}/config/i3/utils.py  OR",
        "",
        f"{'' if (theme_available and config.i3.borders.matugen) else '# '}client.focused          {hex_color} {hex_color} {hex_color} {hex_color}",
        "# client.focused_inactive #ff0000 #ff0000 #ff0000 #ff0000",
        "# client.unfocused        #ff0000 #ff0000 #ff0000 #ff0000",
        "# client.urgent           #ff0000 #ff0000 #ff0000 #ff0000",
    ]

    # atomic
    temp_path = BORDERS_CONF_PATH.with_suffix(".tmp")
    with open(temp_path, "w") as f:
        f.write("\n".join(border_conf))
    os.replace(temp_path, BORDERS_CONF_PATH)

    if reload:
        _reload_i3()


def generate_i3_keybinds(bindings: list[KeyBinding]) -> str:
    lines = [
        "# CAUTION: This file has been auto-generated by Zenith Shell.",
        "# Any manual changes WILL BE OVERWRITTEN on the next startup.",
        "# To change these bindings, edit I3_KEYBINDINGS in:",
        f"#   {ROOT_DIR}/config/bindings.py",
        "",
    ]

    for b in bindings:
        lines.append(
            f"bindsym {b.key} exec {'' if IS_WAYLAND else '--no-startup-id'} {b.command}"
        )

    return "\n".join(lines)


def ensure_i3_config_includes_glob_dir(config_path: Path, include_dir: Path):
    include_line = f"include {include_dir}/*.conf"

    if not config_path.exists():
        logger.warning("{} config not found at {}. Creating new one.", WM, config_path)
        config_path.write_text(f"{include_line}\n")
        return

    content = config_path.read_text()

    if include_line not in content:
        logger.info("Adding include line to {} config", WM)
        # start on a new line
        suffix = "\n" if not content.endswith("\n") else ""
        with open(config_path, "a") as f:
            f.write(f"{suffix}# globbing all .conf in /conf.d\n{include_line}\n")
    else:
        logger.debug("{} config already contains include line", WM)


def get_i3_config_path() -> Path:
    # Commented this out because I dont wanna be making changes
    # to configs that are not intended to be touched...
    # try:
    #     conn = get_i3_connection()

    #     # Send the GET_VERSION request
    #     reply = conn.send_command("", I3MessageType.GET_VERSION)

    #     if reply.is_ok and isinstance(reply.reply, dict):
    #         # Extract the path from the reply dictionary
    #         path_str = reply.reply.get("loaded_config_file_name")
    #         if path_str:
    #             return Path(path_str)

    #     raise I3Error("Path not found in IPC version reply")

    # except Exception as e:
    #     logger.error(f"Could not determine i3 config path via IPC: {e}")
    #     # Fallback to the most common default
    #     return Path("~/.config/i3/config").expanduser()

    return CONFIG_PATH


def ensure_i3_paths():
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_GLOB_PATH.mkdir(parents=True, exist_ok=True)


def generate_i3_keybinds_config(reload: bool = False):
    logger.debug("Setting {} keybinds", WM)

    ensure_i3_paths()
    main_config_path = get_i3_config_path()

    try:
        ensure_i3_config_includes_glob_dir(main_config_path, CONFIG_GLOB_PATH)

        try:
            i3_config_node: _ConfigNode = config.bindings.i3
            overrides = i3_config_node.get_all()
        except AttributeError:
            logger.error("Failed to load {}wm keybind overrides", WM)
            overrides = {}

        bindings = apply_keybinding_overrides(I3_KEYBINDINGS, overrides)

        # TODO
        # validate_keybindings(bindings)
        config_str = generate_i3_keybinds(bindings)

        # atomic
        temp_path = KEYBINDS_CONF_PATH.with_suffix(".tmp")
        with open(temp_path, "w") as f:
            f.write(config_str)
        os.replace(temp_path, KEYBINDS_CONF_PATH)

        if reload:
            _reload_i3()

    except Exception as e:
        logger.error("Failed to apply keybindings: {}", e)


def generate_i3_gaps_and_borders_config():
    lines = []

    gaps_config = config.i3.gaps
    if gaps_config.enabled:
        lines.append("# gaps")
        for prop, val in gaps_config.props.get_all().items():
            lines.append(f"gaps {prop} {val}px")
            if IS_WAYLAND:
                exec_shell_command_async(f"swaymsg gaps {prop} all set {val}")
        lines.append("")

    border_config = config.i3.borders
    if border_config.enabled:
        lines.append("# borders")
        lines.append(f"default_border pixel {border_config.props.border_width}")
        lines.append("default_floating_border none")
        lines.append("")

        if config.i3.borders.props.smart_borders:
            lines.append("smart_borders on")
            lines.append("")

    if IS_WAYLAND:
        # settings window
        config_block = [
            "# floating settings win",
            f'for_window [app_id="{SHELL_NAME}-settings"] {{',
            "    floating enable",
            "    border none",
        ]
        if is_swayfx():
            config_block.extend(
                [
                    "    shadows disable",
                    "    blur disable",
                ]
            )
        config_block.append("}")
        lines.append("\n".join(config_block))

    return "\n".join(lines)


def generate_i3_general_config(reload: bool = False):
    ensure_i3_paths()
    main_config_path = get_i3_config_path()

    lines = [
        "# CAUTION: This file has been auto-generated by Zenith Shell.",
        "# Any manual changes WILL BE OVERWRITTEN on the next startup.",
        "# To change these bindings, edit:",
        f"#   {ROOT_DIR}/config/config.json",
        "",
    ]

    try:
        ensure_i3_config_includes_glob_dir(main_config_path, CONFIG_GLOB_PATH)

        logger.debug("Setting i3 borders and gaps")
        lines.append(generate_i3_gaps_and_borders_config())

        # atomic
        temp_path = GENERAL_CONF_PATH.with_suffix(".tmp")
        with open(temp_path, "w") as f:
            f.write("\n".join(lines) + "\n")
        os.replace(temp_path, GENERAL_CONF_PATH)

        if reload:
            _reload_i3()

    except Exception as e:
        logger.error("Failed to generate {} general config: {}", WM, e)


def add_shell_startup_to_i3_config():
    ensure_i3_paths()
    include_line = f"# {SHELL_NAME} startup\nexec {'' if IS_WAYLAND else '--no-startup-id'} {SHELL_NAME + '-shell'}"
    config_path = get_i3_config_path()

    if not config_path.exists():
        logger.warning("{} config not found at {}. Creating new one.", WM, config_path)
        config_path.write_text(f"{include_line}\n")
        return

    content = config_path.read_text()

    if include_line not in content:
        logger.info("Adding {} startup to {} config", SHELL_NAME, WM)
        # start on a new line
        prefix = "\n" if content and not content.endswith("\n") else ""

        with open(config_path, "a") as f:
            f.write(f"\n{prefix}{include_line}\n")
    else:
        logger.debug("{} config already contains {} startup", WM, SHELL_NAME)


def is_swayfx() -> bool:
    from fabric.i3.service import I3MessageType

    reply = get_i3_connection().send_command("", I3MessageType.GET_VERSION)
    if reply.is_ok and isinstance(reply.reply, dict):
        return (
            "sway_original_version" in reply.reply
            and reply.reply.get("variant") == "sway"
        )
    return False
